### ISSUE TITLE
[Question] How to display html from string

### ISSUE THREAD

**Issue by hybridherbst** [webview/webview_csharp#8]
It seems the "official" way to do this is to call
```
.Navigate(new HtmlContent(myHtmlString)),
```
however, that throws and exception:
```
Unhandled exception. System.UriFormatException: Invalid URI: The Uri string is too long.
   at System.UriHelper.EscapeString(String input, Int32 start, Int32 end, Char[] dest, Int32& destPos, Boolean isUriString, Char force1, Char force2, Char rsvd)
   at System.Uri.EscapeDataString(String stringToEscape)
   at SharpWebview.Content.HtmlContent.ToWebviewUrl()
   at SharpWebview.Webview.Navigate(IWebviewContent webviewContent)
```

Seems the html content is passed in as Url instead of loading the html directly?

Using https://github.com/webview-cs/webview-cs I was able to directly call `Content.FromHtml(myHtmlString)` which worked but those bindings seem to not be "official" so I'd like to use this repo here.

**Comment by geaz** [comment]
I'm on vacation at the moment and the available internet connection is pretty poor. Please wait a week until I travel to a place with a hopefully better connection. Or in the meantime, if possible, paste your html string to a file and use the "HostedContent".

**Comment by hybridherbst** [comment]
I tried doing that but the issue is that this requires the additional permissions, which kind of defeats the purpose of easy installation / usage.

Another option would be to use a UrlContent with a file:// scheme, but that does not seem to be possible.

Happy vacationing! 🎈

**Comment by geaz** [comment]
Hey! I was just able to try to reproduce the problem, but in my test it worked as it should...
I used a minimal example

`.Navigate(new HtmlContent("<html><head><title>test</title></head><p>test</p></html>"))`

and one with an absurdly long text. Both worked as expected. Are you able to provide the none working example?

**Comment by geaz** [comment]
Closing due to inactivity.
